name = "RNGAI"
uid = "faf0863e-9577-ba0d-bb43-8d82b622f1c0"
version = 45
copyright = "2019 relentless"
description = "RNG Standard AI, this AI is designed for 5km and 10km ranked style maps. Now supports 20km maps. Requires Uveso AI to be enabled and generating land path makers."
author = "relentless"
url = ""
icon = "/mods/RNGAI/icon.jpg"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }