name = "RNGAI"
uid = "7f17664d-45b7-436b-995d-d5a387a311ad"
version = 7
copyright = "2019 relentless"
description = "RNG Standard AI, this AI is designed for 5km and 10km ranked style maps. Currently does not support 20km+ and water maps. Requires Uveso AI to be enabled and generating land path makers."
author = "relentless"
url = ""
icon = "/mods/RNGAI/icon.jpg"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }