name = "RNGAI"
uid = "65633f28-2674-4cb4-baae-bf4a76b6d3f5"
version = 6
copyright = "2019 relentless"
description = "RNG Standard AI, this AI is designed for 5km and 10km ranked style maps. Currently does not support 20km+ and water maps. Requires Uveso AI to be enabled and generating land path makers."
author = "relentless"
url = ""
icon = "/mods/RNGAI/icon.jpg"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }